import type { ClassCode } from "./classes";

export type OfficialRow = {
  classcode: ClassCode;
  classno: string;
  enname: string;
  chname: string;
  sex: "F" | "M";
  chiGroup: string;
  engGroup: string;
  mathGroup: string;
};

/** 2026-2027 中一／中二分組上課名單（31/8 及 4/9 定稿）。 */
const ROWS: [ClassCode, string, string, string, "F" | "M", string, string, string][] = [
  ['1A', '1', 'BAI JINGYUE', '白璟鉞', 'F', '1A', '1ABCD2', '1A'],
  ['1A', '2', 'CHAN CHEUK YU', '陳焯茹', 'F', '1A', '1A', '1A'],
  ['1A', '3', 'CHEN TIM YAN', '陳甜欣', 'F', '1ABCD1', '1A', '1A'],
  ['1A', '4', 'CHEUNG YU TUNG', '張宇彤', 'F', '1A', '1A', '1A'],
  ['1A', '5', 'CHUK CHIN SHUN', '祝千舜', 'F', '1A', '1A', '1A'],
  ['1A', '6', 'KWOK SUM YAU', '郭琛悠', 'F', '1ABCD1', '1A', '1A'],
  ['1A', '7', 'LAU JENG YUET', '劉臻悦', 'F', '1A', '1A', '1A'],
  ['1A', '8', 'LEUNG HIU LAAM', '梁曉嵐', 'F', '1A', '1ABCD1', '1A'],
  ['1A', '9', 'LI HIU YIN', '李曉然', 'F', '1A', '1ABCD2', '1A'],
  ['1A', '10', 'LUO JIA JIA', '羅嘉嘉', 'F', '1A', '1ABCD2', '1A'],
  ['1A', '11', 'NG KA KI', '吳家棋', 'F', '1ABCD1', '1A', '1A'],
  ['1A', '12', 'SABOOR AIMEN', '薩艾敏', 'F', '1A', '1ABCD1', '1A'],
  ['1A', '13', 'TSE MAN SUM KIMI', '謝岷芯', 'F', '1A', '1ABCD1', '1A'],
  ['1A', '14', 'WONG SZE WING', '黃施穎', 'F', '1A', '1A', '1A'],
  ['1A', '15', 'YIP MAN CHING', '葉憫程', 'F', '1ABCD1', '1ABCD1', '1A'],
  ['1A', '16', 'ZHANG BAOYU', '張宝予', 'F', '1ABCD1', '1A', '1A'],
  ['1A', '17', 'AU CHUN HIN', '歐俊軒', 'M', '1A', '1A', '1A'],
  ['1A', '18', 'CHAN HO TIN', '陳昊天', 'M', '1A', '1A', '1A'],
  ['1A', '19', 'CHAN YIK LONG', '陳奕朗', 'M', '1A', '1A', '1A'],
  ['1A', '20', 'CHEUNG CHUN CHING', '張溱澄', 'M', '1A', '1A', '1A'],
  ['1A', '21', 'DENG JIALANG', '鄧嘉朗', 'M', '1A', '1A', '1A'],
  ['1A', '22', 'LAM SZE SHING', '林思誠', 'M', '1ABCD2', '1A', '1A'],
  ['1A', '23', 'LEE CHUN YIU', '李俊耀', 'M', '1A', '1A', '1A'],
  ['1A', '24', 'LI WAI HO', '黎瑋豪', 'M', '1A', '1A', '1A'],
  ['1A', '25', 'MAK HO WAI OWEN', '麥皓維', 'M', '1A', '1ABCD1', '1A'],
  ['1A', '26', 'PANG YU', '彭譽', 'M', '1A', '1ABCD2', '1A'],
  ['1A', '27', 'TONG YAU WAI', '湯友維', 'M', '1ABCD1', '1A', '1A'],
  ['1A', '28', 'WONG TSZ HO', '黃子皜', 'M', '1ABCD2', '1A', '1A'],
  ['1A', '29', 'WU YAN HEI', '吳欣曦', 'M', '1ABCD1', '1A', '1A'],
  ['1A', '30', 'YIP MAN TSAN', '葉旻瓚', 'M', '1ABCD1', '1A', '1A'],
  ['1A', '31', 'YUEN NGO TING KOBE', '袁傲庭', 'M', '1A', '1ABCD2', '1A'],
  ['1A', '32', 'ZHANG RUIHENG', '張睿恒', 'M', '1ABCD1', '1A', '1A'],
  ['1B', '1', 'CHIU TSZ KIU', '趙紫喬', 'F', '1B', '1ABCD1', '1B'],
  ['1B', '2', 'CHOW WING YAN', '周泳欣', 'F', '1B', '1ABCD2', '1B'],
  ['1B', '3', 'CHUNG UEN CHUN', '鍾宛真', 'F', '1ABCD2', '1ABCD2', '1B'],
  ['1B', '4', 'FUNG TSZ CHING', '馮芷晴', 'F', '1B', '1B', '1B'],
  ['1B', '5', 'KWOK TEAH', '郭素', 'F', '1B', '1B', '1B'],
  ['1B', '6', 'LEE CHEUK YU', '李婥瑜', 'F', '1B', '1B', '1B'],
  ['1B', '7', 'LI YEUK LAM', '李若琳', 'F', '1ABCD2', '1ABCD1', '1B'],
  ['1B', '8', 'LIU ANGEL', '廖安琪', 'F', '1B', '1ABCD1', '1B'],
  ['1B', '9', 'MA TSZ YU', '馬子雩', 'F', '1B', '1B', '1B'],
  ['1B', '10', 'NG SUI KWAN JEANA', '吳帥君', 'F', '1B', '1B', '1B'],
  ['1B', '11', 'SHEA CHIN CHING', '佘芊晴', 'F', '1ABCD1', '1B', '1B'],
  ['1B', '12', 'TSUI GRETCHEN', '徐芷穎', 'F', '1B', '1ABCD1', '1B'],
  ['1B', '13', 'WONG TSZ TUNG', '黃芷彤', 'F', '1B', '1B', '1B'],
  ['1B', '14', 'YIP WANG LOK', '葉泓樂', 'F', '1B', '1B', '1B'],
  ['1B', '15', 'YU SHU YEE', '余書儀', 'F', '1ABCD2', '1B', '1B'],
  ['1B', '16', 'CHAN MAN MING', '陳敏明', 'M', '1B', '1B', '1B'],
  ['1B', '17', 'CHAN NOK', '陳諾', 'M', '1ABCD2', '1ABCD2', '1B'],
  ['1B', '18', 'CHAN WO HIM', '陳和謙', 'M', '1ABCD2', '1ABCD1', '1B'],
  ['1B', '19', 'CHAN YUI HEI', '陳睿希', 'M', '1B', '1B', '1B'],
  ['1B', '20', 'CHEUNG MAN CHUN', '張敏俊', 'M', '1B', '1B', '1B'],
  ['1B', '21', 'FENG YUK YIU', '馮鈺堯', 'M', '1B', '1B', '1B'],
  ['1B', '22', 'LAU CHIU HEI JOHNSON', '劉釗熹', 'M', '1B', '1ABCD1', '1B'],
  ['1B', '23', 'LEUNG JING XI', '梁敬禧', 'M', '1B', '1B', '1B'],
  ['1B', '24', 'LI TSZ LOK', '李籽樂', 'M', '1ABCD2', '1B', '1B'],
  ['1B', '25', 'LI YIU KWONG', '李耀光', 'M', '1B', '1ABCD2', '1B'],
  ['1B', '26', 'NG CHEUK ON', '吳倬安', 'M', '1B', '1B', '1B'],
  ['1B', '27', 'NG WAI NOK ERIC', '吳瑋諾', 'M', '1B', '1ABCD1', '1B'],
  ['1B', '28', 'TAI TSZ CHUN', '戴釨晉', 'M', '1B', '1ABCD1', '1B'],
  ['1B', '29', 'TSANG PAK HEI', '曾柏希', 'M', '1B', '1B', '1B'],
  ['1B', '30', 'WU WAI SHING', '胡偉城', 'M', '1ABCD2', '1B', '1B'],
  ['1B', '31', 'XIA AUSTIN', '夏子恒', 'M', '1B', '1B', '1B'],
  ['1B', '32', 'YUEN CHUN HIM', '袁駿謙', 'M', '1ABCD2', '1ABCD2', '1B'],
  ['1C', '1', 'CHAN SIN MAN', '陳善雯', 'F', '1C', '1C', '1C'],
  ['1C', '2', 'CHEUNG HOI YING', '張鎧瀠', 'F', '1ABCD2', '1ABCD2', '1C'],
  ['1C', '3', 'CHOI CHEUK LAM JOVIA', '蔡焯霖', 'F', '1C', '1C', '1C'],
  ['1C', '4', 'HUANG WAI YING', '黃偉盈', 'F', '1C', '1C', '1C'],
  ['1C', '5', 'LAI HIU YI', '黎曉兒', 'F', '1C', '1C', '1C'],
  ['1C', '6', 'LEE YEUK PING', '李若冰', 'F', '1ABCD1', '1C', '1C'],
  ['1C', '7', 'LI YUEN YING', '李宛螢', 'F', '1ABCD2', '1ABCD2', '1C'],
  ['1C', '8', 'LIU YUYAN', '劉語嫣', 'F', '1C', '1C', '1CD'],
  ['1C', '9', 'MAK HEI YU', '麥僖洳', 'F', '1ABCD1', '1C', '1C'],
  ['1C', '10', 'MOK HUI FEI', '莫栩菲', 'F', '1ABCD2', '1C', '1C'],
  ['1C', '11', 'POON TSZ KIU KRISTY', '潘梓喬', 'F', '1ABCD1', '1C', '1CD'],
  ['1C', '12', 'TAM TSZ NI', '譚芷妮', 'F', '1C', '1C', '1CD'],
  ['1C', '13', 'WONG CHING MAN', '黃靖雯', 'F', '1ABCD1', '1C', '1C'],
  ['1C', '14', 'WU TSZ CHING', '伍芷晴', 'F', '1C', '1ABCD2', '1CD'],
  ['1C', '15', 'YUEN SUM NOK', '阮琛諾', 'F', '1C', '1C', '1CD'],
  ['1C', '16', 'BUDI PARVAT AMARTMONTREE', '吳子傑', 'M', '1ABCD2', '1C', '1C'],
  ['1C', '17', 'CHAN SZE HON', '陳思翰', 'M', '1ABCD2', '1ABCD2', '1C'],
  ['1C', '18', 'CHAN TSUN HO', '陳浚灝', 'M', '1C', '1C', '1C'],
  ['1C', '19', 'CHEUNG WAI CHUN', '張瑋竣', 'M', '1C', '1C', '1CD'],
  ['1C', '20', 'CHOI WING FAI', '蔡榮輝', 'M', '1C', '1C', '1C'],
  ['1C', '21', 'KWONG CHEUK FAN', '鄺卓帆', 'M', '1C', '1C', '1CD'],
  ['1C', '22', 'LEE CHIN HANG', '李展恒', 'M', '1C', '1ABCD2', '1C'],
  ['1C', '23', 'LEUNG TSZ CHUN', '梁梓堻', 'M', '1C', '1C', '1CD'],
  ['1C', '24', 'LEUNG YAT LONG', '梁日朗', 'M', '1C', '1ABCD1', '1C'],
  ['1C', '25', 'LIN ZIBO', '林梓煿', 'M', '1C', '1C', '1CD'],
  ['1C', '26', 'LO TSZ HIN', '羅梓軒', 'M', '1ABCD2', '1C', '1C'],
  ['1C', '27', 'MAN SHUN KIU', '文遜翹', 'M', '1ABCD2', '1C', '1C'],
  ['1C', '28', 'TAM CHING HIM', '譚証謙', 'M', '1C', '1C', '1C'],
  ['1C', '29', 'TSANG HOI NAM', '曾愷楠', 'M', '1ABCD2', '1ABCD1', '1C'],
  ['1C', '30', 'XU WEI XUAN DICKSON', '許煒軒', 'M', '1C', '1ABCD2', '1C'],
  ['1C', '31', 'YEUNG DESMOND MARCO', '楊瀚霆', 'M', '1ABCD2', '1ABCD2', '1C'],
  ['1C', '32', 'YIP MIU YAM', '葉淼鑫', 'M', '1C', '1ABCD2', '1CD'],
  ['1D', '1', 'CHAN YUEN LAM', '陳婉琳', 'F', '1D', '1D', '1D'],
  ['1D', '2', 'CHUI WAN LAM', '徐韻琳', 'F', '1D', '1D', '1D'],
  ['1D', '3', 'HUANG ZILIN', '黄子林', 'F', '1ABCD1', '1D', '1D'],
  ['1D', '4', 'LAM YU CHING', '林雨晴', 'F', '1ABCD1', '1ABCD1', '1D'],
  ['1D', '5', 'LAU SUM MOCHA', '劉心', 'F', '1D', '1D', '1D'],
  ['1D', '6', 'LEUNG BELLA', '梁貝娜', 'F', '1ABCD1', '1D', '1D'],
  ['1D', '7', 'LUI YAU', '呂悠', 'F', '1ABCD1', '1ABCD2', '1CD'],
  ['1D', '8', 'MAK TSZ TUNG', '麥芷浵', 'F', '1D', '1D', '1D'],
  ['1D', '9', 'PANG TSZ YAN', '彭芷茵', 'F', '1D', '1D', '1D'],
  ['1D', '10', 'TO CHEUK YING', '杜綽凝', 'F', '1D', '1D', '1D'],
  ['1D', '11', 'WONG NGA CHING', '黃雅晴', 'F', '1D', '1D', '1D'],
  ['1D', '12', 'YANG YIQING', '楊藝晴', 'F', '1D', '1D', '1D'],
  ['1D', '13', 'ZENG YUK YING', '曾鈺英', 'F', '1D', '1ABCD2', '1D'],
  ['1D', '14', 'AU HOI CHEUK', '區愷倬', 'M', '1D', '1D', '1D'],
  ['1D', '15', 'CHAN CHING HO', '陳正皓', 'M', '1D', '1D', '1CD'],
  ['1D', '16', 'CHAN PAK HO PACO', '陳柏澔', 'M', '1D', '1D', '1D'],
  ['1D', '17', 'CHAN WAI WING', '陳暐穎', 'M', '1D', '1D', '1CD'],
  ['1D', '18', 'CHANG YUEN HO', '張玄皓', 'M', '1ABCD2', '1ABCD1', '1CD'],
  ['1D', '19', 'CHENG YIK NAM', '鄭翊男', 'M', '1D', '1D', '1CD'],
  ['1D', '20', 'FU KA LAM', '傅嘉林', 'M', '1ABCD1', '1D', '1CD'],
  ['1D', '21', 'LAM KING TIN', '林敬天', 'M', '1D', '1ABCD1', '1CD'],
  ['1D', '22', 'LAU YAT LAI', '劉日禮', 'M', '1D', '1D', '1D'],
  ['1D', '23', 'LEE CHING FUNG', '利青峯', 'M', '1D', '1D', '1D'],
  ['1D', '24', 'LUI PAK YIN', '呂柏言', 'M', '1D', '1D', '1D'],
  ['1D', '25', 'NG CHI HANG ADAM', '吳智恆', 'M', '1ABCD1', '1ABCD1', '1CD'],
  ['1D', '26', 'NG WAI SEN', '吳椲晨', 'M', '1D', '1ABCD1', '1D'],
  ['1D', '27', 'TANG CHUN HANG', '鄧晉亨', 'M', '1D', '1D', '1CD'],
  ['1D', '28', 'WAN YAN KIU', '温胤翹', 'M', '1ABCD1', '1D', '1CD'],
  ['1D', '29', 'WONG HO YUI', '黃浩睿', 'M', '1D', '1ABCD2', '1CD'],
  ['1D', '30', 'XIANG YU', '向雨', 'M', '1ABCD2', '1ABCD1', '1D'],
  ['1D', '31', 'YIU PAK KEI', '姚泊岐', 'M', '1D', '1D', '1D'],
  ['1D', '32', 'YUEN TSZ HO', '袁梓灝', 'M', '1D', '1D', '1D'],
  ['2A', '1', 'CHAK WAI TING', '翟慧婷', 'F', '2A', '2A', '2A'],
  ['2A', '2', 'CHAN HO YING', '陳顥熒', 'F', '2A', '2A', '2A'],
  ['2A', '3', 'CHAN YAU HEI YOVINA', '陳柔羲', 'F', '2A', '2A', '2A'],
  ['2A', '4', 'CHEUNG CHI CHING', '張淽晴', 'F', '2A', '2A', '2A'],
  ['2A', '5', 'CHOW YAN YIN', '周殷言', 'F', '2A', '2A', '2A'],
  ['2A', '6', 'HO CHING WAN', '何靜昀', 'F', '2A', '2A', '2A'],
  ['2A', '7', 'HO YUEN TING', '何婉婷', 'F', '2A', '2A', '2A'],
  ['2A', '8', 'HUANG SHUXIAN', '黃淑賢', 'F', '2A', '2A', '2A'],
  ['2A', '9', 'IONG HOI LAM', '容凱霖', 'F', '2A', '2A', '2A'],
  ['2A', '10', 'KWOK TSZ LAM', '郭梓琳', 'F', '2A', '2A', '2A'],
  ['2A', '11', 'LEUNG YU YIN', '梁語嫣', 'F', '2A', '2A', '2A'],
  ['2A', '12', 'SIU TSZ YAU', '蕭紫柔', 'F', '2A', '2A', '2A'],
  ['2A', '13', 'TANG CHO CHING', '鄧楚澄', 'F', '2A', '2A', '2A'],
  ['2A', '14', 'TONG HEI YI', '唐曦兒', 'F', '2A', '2A', '2A'],
  ['2A', '15', 'WONG TSZ KIU', '王祉喬', 'F', '2A', '2A', '2A'],
  ['2A', '16', 'WONG YUK SHUEN', '王鈺璇', 'F', '2A', '2A', '2A'],
  ['2A', '17', 'YE PUI YU', '葉佩瑜', 'F', '2A', '2A', '2A'],
  ['2A', '18', 'YIP KA PUI', '葉加貝', 'F', '2A', '2A', '2A'],
  ['2A', '19', 'ZHOU YONGHUI', '周永慧', 'F', '2A', '2A', '2A'],
  ['2A', '20', 'CHENG MING SANG', '鄭明生', 'M', '2A', '2A', '2A'],
  ['2A', '21', 'FONG HAU MAN', '方孝文', 'M', '2A', '2A', '2A'],
  ['2A', '22', 'LAM CHING HO ANGUS', '林靖皓', 'M', '2A', '2A', '2A'],
  ['2A', '23', 'LAM TSZ POK', '林子博', 'M', '2A', '2A', '2A'],
  ['2A', '24', 'LAM WING HIN', '林詠軒', 'M', '2A', '2A', '2A'],
  ['2A', '25', 'LAM YAU FUNG', '林祐鋒', 'M', '2A', '2A', '2A'],
  ['2A', '26', 'LI SIU HANG', '李兆衡', 'M', '2A', '2A', '2A'],
  ['2A', '27', 'LI WEI JUN', '李威筠', 'M', '2A', '2A', '2A'],
  ['2A', '28', 'MAK CHING YIN', '麥正彥', 'M', '2A', '2A', '2A'],
  ['2A', '29', 'SHALABAEV IVAN', '伊万', 'M', '2A', '2A', '2A'],
  ['2A', '30', 'SHUM YAT HEI', '岑日希', 'M', '2A', '2A', '2A'],
  ['2A', '31', 'XI LIHAO', '席立昊', 'M', '2A', '2A', '2A'],
  ['2A', '32', 'YAU HO YU ERIC', '邱皓宇', 'M', '2A', '2A', '2A'],
  ['2A', '33', 'YEUNG TSZ YU', '楊梓輿', 'M', '2A', '2A', '2A'],
  ['2B', '1', 'AU CHI CHING', '區智晴', 'F', '2B', '2B', '2B'],
  ['2B', '2', 'CHAN CHIN YUET', '陳千悅', 'F', '2B', '2B', '2B'],
  ['2B', '3', 'CHEN XIAO YAN', '陳晓嫣', 'F', '2B', '2B', '2BCD1'],
  ['2B', '4', 'CHEUNG SIN YU', '張茜瑜', 'F', '2B', '2BCD', '2B'],
  ['2B', '5', 'HO YAN YING', '何恩盈', 'F', '2B', '2B', '2B'],
  ['2B', '6', 'JIA YUE', '賈玥', 'F', '2B', '2B', '2BCD1'],
  ['2B', '7', 'LAU TSZ LAM', '劉芷琳', 'F', '2B', '2B', '2B'],
  ['2B', '8', 'PAK YUET YEE', '白悅頤', 'F', '2B', '2BCD', '2BCD2'],
  ['2B', '9', 'TAM MAN YING NIKI FEBRY AZURA', '譚文瑛', 'F', '2B', '2BCD', '2B'],
  ['2B', '10', 'TANG PUI YAN', '鄧沛欣', 'F', '2B', '2B', '2BCD2'],
  ['2B', '11', 'TO HIU TUNG', '陶曉曈', 'F', '2B', '2BCD', '2B'],
  ['2B', '12', 'WU HOI KEI', '胡凱淇', 'F', '2B', '2B', '2B'],
  ['2B', '13', 'ZHANG KA SIN JOYCE', '張嘉倩', 'F', '2B', '2B', '2B'],
  ['2B', '14', 'CHAN KA MING', '陳嘉明', 'M', '2B', '2B', '2B'],
  ['2B', '15', 'CHAN KA WING', '陳嘉榮', 'M', '2B', '2B', '2B'],
  ['2B', '16', 'CHAU ADRIAN', '周柏希', 'M', '2B', '2B', '2B'],
  ['2B', '17', 'CHEUNG TING HIN', '張庭騫', 'M', '2B', '2B', '2B'],
  ['2B', '18', 'LEE CHUN HEI', '李俊熹', 'M', '2B', '2B', '2BCD2'],
  ['2B', '19', 'LO CHUN KIT', '盧俊杰', 'M', '2B', '2BCD', '2B'],
  ['2B', '20', 'LUK HIU NAM', '陸曉楠', 'M', '2B', '2B', '2BCD1'],
  ['2B', '21', 'NG HO HIM', '吳皓謙', 'M', '2B', '2B', '2B'],
  ['2B', '22', 'NG YAT HEI', '吳日希', 'M', '2B', '2B', '2B'],
  ['2B', '23', 'SIU KING HIN', '蕭敬騫', 'M', '2B', '2B', '2BCD1'],
  ['2B', '24', 'TANG MING WAI', '鄧銘葦', 'M', '2B', '2B', '2B'],
  ['2B', '25', 'WONG KWUN LAM', '黃冠霖', 'M', '2B', '2B', '2BCD2'],
  ['2B', '26', 'WONG TSZ HONG', '王梓匡', 'M', '2B', '2B', '2BCD1'],
  ['2B', '27', 'XU WEI JUN KASON', '許煒峻', 'M', '2B', '2B', '2B'],
  ['2B', '28', 'YEUNG CHUN HEI', '楊焌琋', 'M', '2B', '2BCD', '2BCD2'],
  ['2B', '29', 'YIU FU SUM', '姚富森', 'M', '2B', '2B', '2BCD2'],
  ['2B', '30', 'ZHANG JUNBAO', '張君寶', 'M', '2B', '2B', '2BCD1'],
  ['2C', '1', 'CHAN CHEUK YING', '陳卓迎', 'F', '2CD1', '2C', '2C'],
  ['2C', '2', 'CHAN TSZ YAN', '陳址昕', 'F', '2CD1', '2C', '2C'],
  ['2C', '3', 'CHENG TSZ SIN', '鄭紫善', 'F', '2CD1', '2BCD', '2BCD2'],
  ['2C', '4', 'CHEUNG HOI LAM', '張凱琳', 'F', '2CD1', '2C', '2C'],
  ['2C', '5', 'CHOW KA YAU', '周嘉悠', 'F', '2CD3', '2BCD', '2C'],
  ['2C', '6', 'CHOW YUEN KI', '周琬淇', 'F', '2CD3', '2BCD', '2C'],
  ['2C', '7', 'KO YING NING', '高櫻寧', 'F', '2CD1', '2C', '2BCD2'],
  ['2C', '8', 'LIN LILING', '林麗靈', 'F', '2CD1', '2C', '2C'],
  ['2C', '9', 'LIU WING SHUEN', '廖穎璇', 'F', '2CD1', '2C', '2C'],
  ['2C', '10', 'LO HO CHING', '盧可澄', 'F', '2CD2', '2C', '2C'],
  ['2C', '11', 'TAI PUI KI PEGGY', '戴貝琪', 'F', '2CD1', '2C', '2C'],
  ['2C', '12', 'WONG LOK TUNG', '黃洛彤', 'F', '2CD2', '2C', '2C'],
  ['2C', '13', 'WONG MING SUM', '黃銘芯', 'F', '2CD1', '2BCD', '2C'],
  ['2C', '14', 'CAI ZHENXUAN', '蔡振軒', 'M', '2CD1', '2C', '2C'],
  ['2C', '15', 'CHAN KEI KIT', '陳紀杰', 'M', '2CD3', '2BCD', '2BCD2'],
  ['2C', '16', 'GABAYAN ENOCH GUTSY', '李以諾', 'M', '2CD3', '2BCD', '2C'],
  ['2C', '17', 'HO HO YU', '何浩渝', 'M', '2CD2', '2C', '2BCD2'],
  ['2C', '18', 'KWAN CHUNG HIN', '關仲軒', 'M', '2CD1', '2C', '2C'],
  ['2C', '19', 'LAI KA LOK', '黎家諾', 'M', '2CD3', '2C', '2BCD2'],
  ['2C', '20', 'LAM LOK YIU', '林洛銚', 'M', '2CD1', '2C', '2BCD2'],
  ['2C', '21', 'LEUNG PAK HO', '梁珀豪', 'M', '2CD3', '2C', '2C'],
  ['2C', '22', 'LI HO YIN', '李浩然', 'M', '2CD3', '2C', '2C'],
  ['2C', '23', 'LI TSZ YEUNG', '李梓揚', 'M', '2CD1', '2C', '2C'],
  ['2C', '24', 'LIN HOI HIN', '林海軒', 'M', '2CD3', '2C', '2BCD2'],
  ['2C', '25', 'WONG KA HEI', '黃嘉希', 'M', '2CD3', '2BCD', '2BCD2'],
  ['2C', '26', 'WONG SHING TSUN', '黃丞浚', 'M', '2CD3', '2C', '2BCD1'],
  ['2C', '27', 'WONG TING HANG', '黃霆鏗', 'M', '2CD2', '2C', '2BCD2'],
  ['2C', '28', 'YEUNG CHUN HEI', '楊俊熙', 'M', '2CD3', '2C', '2C'],
  ['2C', '29', 'YIP CHUN HIN', '葉晉軒', 'M', '2CD3', '2C', '2BCD2'],
  ['2C', '30', 'YU LAI CHING', '余禮呈', 'M', '2CD1', '2BCD', '2BCD1'],
  ['2D', '1', 'AU ELISHA', '區以諾', 'F', '2CD1', '2D', '2BCD1'],
  ['2D', '2', 'CHAN HIU TUNG', '陳曉銅', 'F', '2CD1', '2D', '2D'],
  ['2D', '3', 'CHAU HO LAM', '周可琳', 'F', '2CD1', '2D', '2D'],
  ['2D', '4', 'CHEN YAHUI', '陳雅惠', 'F', '2CD2', '2BCD', '2BCD2'],
  ['2D', '5', 'CHIU HEI CHING', '趙希澄', 'F', '2CD1', '2D', '2D'],
  ['2D', '6', 'CHOI MAN SZE', '蔡敏詩', 'F', '2CD2', '2D', '2BCD1'],
  ['2D', '7', 'FAN HIU CHING', '范曉晴', 'F', '2CD2', '2D', '2BCD1'],
  ['2D', '8', 'HO WING CHI', '何穎芝', 'F', '2CD3', '2BCD', '2D'],
  ['2D', '9', 'LAM TSZ LUI', '林芷蕾', 'F', '2CD2', '2BCD', '2D'],
  ['2D', '10', 'LO HAU KIU', '羅巧喬', 'F', '2CD2', '2D', '2D'],
  ['2D', '11', 'NG CHI LAM', '吳淽琳', 'F', '2CD2', '2D', '2BCD2'],
  ['2D', '12', 'TAN QILING', '譚綺玲', 'F', '2CD3', '2D', '2D'],
  ['2D', '13', 'WANG XINYU', '王芯愉', 'F', '2CD2', '2D', '2D'],
  ['2D', '14', 'WONG TSZ CHING', '黃梓澄', 'F', '2CD1', '2BCD', '2D'],
  ['2D', '15', 'XU ZIHAN', '徐紫涵', 'F', '2CD2', '2D', '2D'],
  ['2D', '16', 'YIU SUM YI', '姚芯沂', 'F', '2CD2', '2D', '2D'],
  ['2D', '17', 'ZENG KAICHUN', '曾楷淳', 'F', '2CD2', '2D', '2BCD1'],
  ['2D', '18', 'ZHENG SIDAN', '鄭斯丹', 'F', '2CD2', '2D', '2BCD1'],
  ['2D', '19', 'CHAN PAK HO', '陳柏昊', 'M', '2CD1', '2BCD', '2BCD1'],
  ['2D', '20', 'CHENG TSZ HIN', '鄭梓軒', 'M', '2CD2', '2D', '2BCD1'],
  ['2D', '21', 'CHEUNG YAT LUNG', '張溢龍', 'M', '2CD3', '2D', '2D'],
  ['2D', '22', 'CHOI TSUN HIN', '蔡浚軒', 'M', '2CD3', '2BCD', '2D'],
  ['2D', '23', 'CHOW KA LONG', '周加朗', 'M', '2CD2', '2D', '2BCD1'],
  ['2D', '24', 'CHOW SAI LOK', '周世樂', 'M', '2CD3', '2BCD', '2BCD2'],
  ['2D', '25', 'KAN CHUN HIN', '簡俊軒', 'M', '2CD2', '2D', '2D'],
  ['2D', '26', 'LAW TSZ KIN', '羅子健', 'M', '2CD3', '2D', '2D'],
  ['2D', '27', 'LIU HOK MING', '劉學明', 'M', '2CD3', '2BCD', '2D'],
  ['2D', '28', 'LO LONG YIN', '盧朗然', 'M', '2CD2', '2D', '2BCD1'],
  ['2D', '29', 'LO TSZ LOK', '盧梓樂', 'M', '2CD1', '2BCD', '2D'],
  ['2D', '30', 'WONG YUEN HAM', '黃遠涵', 'M', '2CD2', '2D', '2D'],
  ['2D', '31', 'YIU TSZ HIM', '姚子謙', 'M', '2CD2', '2BCD', '2BCD1'],
  ['2D', '32', 'ZEE CHAK LAM', '徐澤林', 'M', '2CD2', '2D', '2BCD1'],
];

export const OFFICIAL_ROSTER: OfficialRow[] = ROWS.map(
  ([classcode, classno, enname, chname, sex, chiGroup, engGroup, mathGroup]) => ({
    classcode,
    classno,
    enname,
    chname,
    sex,
    chiGroup,
    engGroup,
    mathGroup,
  }),
);

export const OFFICIAL_COUNT = OFFICIAL_ROSTER.length;
